FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy the requirements file
COPY ./backend/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy the rest of the application code
COPY ./backend .

# Expose the port the app runs on
EXPOSE 8000

# Copy the entrypoint script
COPY ./config/backend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use the entrypoint script to run migrations and start the application
CMD ["/entrypoint.sh"]

# # Start the application
# CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]